
include makeinclude.win32

DIRS = src bin

all:   makeinclude.win32
#	if [ -f bin/$(PRGS) ] ; then
#	  rm bin/$(PRGS)
#	fi
	@for dir in $(DIRS); do\
	    echo "==== Compiling in $$dir ====";\
	    (cd $$dir; make -f Makefile.win32 || break);\
	done
	
clean: makeinclude.win32
	@for dir in $(DIRS); do\
	    echo "==== Cleaning in $$dir ====";\
	    (cd $$dir; make -f Makefile.win32 clean || break);\
	done

install:
	#rm -f ~/bin/$(PRGS)
	cp bin/$(PRGS) ~/bin

run:
	./bin/$(PRGS)
